local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 

-- ----- 
--  BORDER 
-- ---- 

-- -----
--   FONT
-- -----
LSM:Register("font", "Numen", [[Interface\Addons\FojjiCore\font\Numen.ttf]])
LSM:Register("font", "FojjiArcade", [[Interface\Addons\FojjiCore\font\FojjiArcade.ttf]]) 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "fojji Beep", [[Interface\Addons\FojjiCore\sound\Beep.ogg]])
LSM:Register("sound", "fojji Bell", [[Interface\Addons\FojjiCore\sound\Bell.ogg]])
LSM:Register("sound", "fojji Chime", [[Interface\Addons\FojjiCore\sound\Chime.ogg]])
LSM:Register("sound", "fojji Click", [[Interface\Addons\FojjiCore\sound\Click.ogg]])
LSM:Register("sound", "fojji Drop", [[Interface\Addons\FojjiCore\sound\fojjiDrop.ogg]])
LSM:Register("sound", "fojji Gong", [[Interface\Addons\FojjiCore\sound\Gong.ogg]])
LSM:Register("sound", "fojji Heart", [[Interface\Addons\FojjiCore\sound\Heart.ogg]])
LSM:Register("sound", "fojji IM", [[Interface\Addons\FojjiCore\sound\IM.ogg]])
LSM:Register("sound", "fojji Info", [[Interface\Addons\FojjiCore\sound\Info.ogg]])
LSM:Register("sound", "fojji Kachink", [[Interface\Addons\FojjiCore\sound\Kachink.ogg]])
LSM:Register("sound", "fojji Link", [[Interface\Addons\FojjiCore\sound\Link.ogg]])
LSM:Register("sound", "fojji Mario Coin", [[Interface\Addons\FojjiCore\sound\Mario Coin.ogg]])
LSM:Register("sound", "fojji Msg", [[Interface\Addons\FojjiCore\sound\fojjiMsg.ogg]])
LSM:Register("sound", "fojji MultiPop", [[Interface\Addons\FojjiCore\sound\fojjiMultipop.ogg]])
LSM:Register("sound", "fojji MultiPop2", [[Interface\Addons\FojjiCore\sound\fojjiMultiPop2.ogg]])
LSM:Register("sound", "fojji Ogre Death", [[Interface\Addons\FojjiCore\sound\fojjiOgreDeath.ogg]])
LSM:Register("sound", "fojji Pop1", [[Interface\Addons\FojjiCore\sound\fojjiPop1.ogg]])
LSM:Register("sound", "fojji Pop2", [[Interface\Addons\FojjiCore\sound\fojjiPop2.ogg]])
LSM:Register("sound", "fojji Pop3", [[Interface\Addons\FojjiCore\sound\fojjiPop3.ogg]])
LSM:Register("sound", "fojji PopClick", [[Interface\Addons\FojjiCore\sound\fojjiPopClick.ogg]])
LSM:Register("sound", "fojji Ratchet", [[Interface\Addons\FojjiCore\sound\Ratchet.ogg]])
LSM:Register("sound", "fojji Snap", [[Interface\Addons\FojjiCore\sound\fojjiSnap.ogg]])
LSM:Register("sound", "fojji SoftNotice", [[Interface\Addons\FojjiCore\sound\fojjiSoftNotice.ogg]])
LSM:Register("sound", "fojji Swoosh", [[Interface\Addons\FojjiCore\sound\fojjiSwoosh.ogg]])
LSM:Register("sound", "fojji Text1", [[Interface\Addons\FojjiCore\sound\Text1.ogg]])
LSM:Register("sound", "fojji Text2", [[Interface\Addons\FojjiCore\sound\Text2.ogg]])
LSM:Register("sound", "fojji Ting", [[Interface\Addons\FojjiCore\sound\fojjiTing.ogg]])
LSM:Register("sound", "fojji Video Game Death", [[Interface\Addons\FojjiCore\sound\fojjiVideoGameDeath.ogg]])
LSM:Register("sound", "fojji |cFFFF00001|r", [[Interface\Addons\FojjiCore\sound\1.ogg]])
LSM:Register("sound", "fojji |cFFFF00001 Left|r", [[Interface\Addons\FojjiCore\sound\1 Left.ogg]])
LSM:Register("sound", "fojji |cFFFF00002|r", [[Interface\Addons\FojjiCore\sound\2.ogg]])
LSM:Register("sound", "fojji |cFFFF00002 Left|r", [[Interface\Addons\FojjiCore\sound\2 Left.ogg]])
LSM:Register("sound", "fojji |cFFFF00003|r", [[Interface\Addons\FojjiCore\sound\3.ogg]])
LSM:Register("sound", "fojji |cFFFF00004|r", [[Interface\Addons\FojjiCore\sound\4.ogg]])
LSM:Register("sound", "fojji |cFFFF00005|r", [[Interface\Addons\FojjiCore\sound\5.ogg]])
LSM:Register("sound", "fojji |cFFFF00006|r", [[Interface\Addons\FojjiCore\sound\6.ogg]])
LSM:Register("sound", "fojji |cFFFF00007|r", [[Interface\Addons\FojjiCore\sound\7.ogg]])
LSM:Register("sound", "fojji |cFFFF00008|r", [[Interface\Addons\FojjiCore\sound\8.ogg]])
LSM:Register("sound", "fojji |cFFFF00009|r", [[Interface\Addons\FojjiCore\sound\9.ogg]])
LSM:Register("sound", "fojji |cFFFE000010|r", [[Interface\Addons\FojjiCore\sound\10.ogg]])
LSM:Register("sound", "fojji |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\FojjiCore\sound\01.ogg]])
LSM:Register("sound", "fojji |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\FojjiCore\sound\02.ogg]])
LSM:Register("sound", "fojji |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\FojjiCore\sound\03.ogg]])
LSM:Register("sound", "fojji |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\FojjiCore\sound\04.ogg]])
LSM:Register("sound", "fojji |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\FojjiCore\sound\05.ogg]])
LSM:Register("sound", "fojji |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\FojjiCore\sound\06.ogg]])
LSM:Register("sound", "fojji |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\FojjiCore\sound\07.ogg]])
LSM:Register("sound", "fojji |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\FojjiCore\sound\08.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Add|r", [[Interface\Addons\FojjiCore\sound\Add.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Adds|r", [[Interface\Addons\FojjiCore\sound\Adds.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Adds Soon|r", [[Interface\Addons\FojjiCore\sound\Adds Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Air Phase|r", [[Interface\Addons\FojjiCore\sound\Air Phase.ogg]])
LSM:Register("sound", "fojji |cFFFF0000AMS|r", [[Interface\Addons\FojjiCore\sound\AMS.ogg]])
LSM:Register("sound", "fojji |cFFFF0000AM Soon|r", [[Interface\Addons\FojjiCore\sound\A M Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000AoE|r", [[Interface\Addons\FojjiCore\sound\AoE.ogg]])
LSM:Register("sound", "fojji |cFFFF0000AoE Soon|r", [[Interface\Addons\FojjiCore\sound\AoE Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000AoE Taunt|r", [[Interface\Addons\FojjiCore\sound\AoE Taunt.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Arcane Blowback|r", [[Interface\Addons\FojjiCore\sound\Arcane Blowback.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Arcanotron|r", [[Interface\Addons\FojjiCore\sound\Arcanotron.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Armor Pen|r", [[Interface\Addons\FojjiCore\sound\Armor Pen.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Armageddon|r", [[Interface\Addons\FojjiCore\sound\Armageddon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Assist|r", [[Interface\Addons\FojjiCore\sound\Assist.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Attack Power|r", [[Interface\Addons\FojjiCore\sound\Attack Power.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Aura Mastery|r", [[Interface\Addons\FojjiCore\sound\Aura Mastery.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Avoid|r", [[Interface\Addons\FojjiCore\sound\Avoid.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Backup|r", [[Interface\Addons\FojjiCore\sound\Backup.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Bait|r", [[Interface\Addons\FojjiCore\sound\Bait.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Barkskin|r", [[Interface\Addons\FojjiCore\sound\Barkskin.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Barrage|r", [[Interface\Addons\FojjiCore\sound\Barrage.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Beacon|r", [[Interface\Addons\FojjiCore\sound\Beacon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Beam|r", [[Interface\Addons\FojjiCore\sound\Beam.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Beam on|r", [[Interface\Addons\FojjiCore\sound\Beam on.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Beams in 5|r", [[Interface\Addons\FojjiCore\sound\Beams in 5.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Behind|r", [[Interface\Addons\FojjiCore\sound\Behind.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Bell|r", [[Interface\Addons\FojjiCore\sound\Bell.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Berserk|r", [[Interface\Addons\FojjiCore\sound\Berserk.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Berserk Soon|r", [[Interface\Addons\FojjiCore\sound\Berserk Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Bite|r", [[Interface\Addons\FojjiCore\sound\Bite.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Bitten|r", [[Interface\Addons\FojjiCore\sound\Bitten.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Blackout|r", [[Interface\Addons\FojjiCore\sound\Blackout.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Blast Soon|r", [[Interface\Addons\FojjiCore\sound\Blast Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Blizzard|r", [[Interface\Addons\FojjiCore\sound\Blizzard.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Block|r", [[Interface\Addons\FojjiCore\sound\Block.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Blowback|r", [[Interface\Addons\FojjiCore\sound\Blowback.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Blowback in 3|r", [[Interface\Addons\FojjiCore\sound\Blowback in 3.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Blue|r", [[Interface\Addons\FojjiCore\sound\Blue.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Boiling|r", [[Interface\Addons\FojjiCore\sound\Boiling.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Bomb|r", [[Interface\Addons\FojjiCore\sound\Bomb.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Bomb Close|r", [[Interface\Addons\FojjiCore\sound\Bomb Close.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Boss|r", [[Interface\Addons\FojjiCore\sound\Boss.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Boss Stunned|r", [[Interface\Addons\FojjiCore\sound\Boss Stunned.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Breath|r", [[Interface\Addons\FojjiCore\sound\Breath.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Breath Soon|r", [[Interface\Addons\FojjiCore\sound\Breath Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Breeze|r", [[Interface\Addons\FojjiCore\sound\Breeze.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Bubble|r", [[Interface\Addons\FojjiCore\sound\Bubble.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Buff|r", [[Interface\Addons\FojjiCore\sound\Buff.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Burning Blood|r", [[Interface\Addons\FojjiCore\sound\Burning Blood.ogg]])
LSM:Register("sound", "fojji |cFFFF0000CC|r", [[Interface\Addons\FojjiCore\sound\CC.ogg]])
LSM:Register("sound", "fojji |cFFFF0000CD|r", [[Interface\Addons\FojjiCore\sound\CD.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Carrot|r", [[Interface\Addons\FojjiCore\sound\Carrot.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Center|r", [[Interface\Addons\FojjiCore\sound\Center.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Chain|r", [[Interface\Addons\FojjiCore\sound\Chain.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Charge|r", [[Interface\Addons\FojjiCore\sound\Charge.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Chemical Bomb|r", [[Interface\Addons\FojjiCore\sound\Chemical Bomb.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Chill on You|r", [[Interface\Addons\FojjiCore\sound\Chill on You.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Cinder on You|r", [[Interface\Addons\FojjiCore\sound\Cinder on You.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Cinders|r", [[Interface\Addons\FojjiCore\sound\Cinders.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Cinders Soon|r", [[Interface\Addons\FojjiCore\sound\Cinders Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Clear|r", [[Interface\Addons\FojjiCore\sound\Clear.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Clear Stack|r", [[Interface\Addons\FojjiCore\sound\Clear Stack.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Click|r", [[Interface\Addons\FojjiCore\sound\ClickTTS.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Cloak|r", [[Interface\Addons\FojjiCore\sound\Cloak.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Coil|r", [[Interface\Addons\FojjiCore\sound\Coil.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Collect|r", [[Interface\Addons\FojjiCore\sound\Collect.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Conductor|r", [[Interface\Addons\FojjiCore\sound\Conductor.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Conductor Soon|r", [[Interface\Addons\FojjiCore\sound\Conductor Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Core|r", [[Interface\Addons\FojjiCore\sound\Core.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Corrupted Adherents|r", [[Interface\Addons\FojjiCore\sound\Corrupted Adherents.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Crackle|r", [[Interface\Addons\FojjiCore\sound\Crackle.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Crackle in 5|r", [[Interface\Addons\FojjiCore\sound\Crackle in 5.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Creations|r", [[Interface\Addons\FojjiCore\sound\Creations.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Creations Soon|r", [[Interface\Addons\FojjiCore\sound\Creations Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Crit|r", [[Interface\Addons\FojjiCore\sound\Crit.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Dance|r", [[Interface\Addons\FojjiCore\sound\Dance.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Dark|r", [[Interface\Addons\FojjiCore\sound\Dark.ogg]])
LSM:Register("sound", "fojji |cFFFF0000D Sac|r", [[Interface\Addons\FojjiCore\sound\D Sac.ogg]])
LSM:Register("sound", "fojji |cFFFF0000D Sac Soon|r", [[Interface\Addons\FojjiCore\sound\D Sac Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Dance|r", [[Interface\Addons\FojjiCore\sound\Dance.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Debuff|r", [[Interface\Addons\FojjiCore\sound\Debuff.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Decay|r", [[Interface\Addons\FojjiCore\sound\Decay.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Decurse|r", [[Interface\Addons\FojjiCore\sound\Decurse.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Defensive|r", [[Interface\Addons\FojjiCore\sound\Defensive.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Deep Breath|r", [[Interface\Addons\FojjiCore\sound\Deep Breath.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Deep Breath 1|r", [[Interface\Addons\FojjiCore\sound\Deep Breath 1.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Deep Breath 2|r", [[Interface\Addons\FojjiCore\sound\Deep Breath 2.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Deep Breath 3|r", [[Interface\Addons\FojjiCore\sound\Deep Breath 3.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Disorient|r", [[Interface\Addons\FojjiCore\sound\Disorient.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Dispell|r", [[Interface\Addons\FojjiCore\sound\Dispell.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Dodge|r", [[Interface\Addons\FojjiCore\sound\Dodge.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Dodge Swirlies|r", [[Interface\Addons\FojjiCore\sound\Dodge Swirlies.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Don't Attack|r", [[Interface\Addons\FojjiCore\sound\Don't Attack.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Double Ooze|r", [[Interface\Addons\FojjiCore\sound\Double Ooze.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Drop|r", [[Interface\Addons\FojjiCore\sound\Drop.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Dont Move|r", [[Interface\Addons\FojjiCore\sound\Dont Move.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Dont Move to Edge|r", [[Interface\Addons\FojjiCore\sound\Move to Edge.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Dot|r", [[Interface\Addons\FojjiCore\sound\Dot.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Earth Shield|r", [[Interface\Addons\FojjiCore\sound\Earth Shield.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Electron|r", [[Interface\Addons\FojjiCore\sound\Electron.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Egg Vulnerable|r", [[Interface\Addons\FojjiCore\sound\Egg Vulnerable.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Empowered Shadows|r", [[Interface\Addons\FojjiCore\sound\Empowered Shadows.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Encased|r", [[Interface\Addons\FojjiCore\sound\Encased.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Engulf|r", [[Interface\Addons\FojjiCore\sound\Engulf.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Enter|r", [[Interface\Addons\FojjiCore\sound\Enter.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Enrage|r", [[Interface\Addons\FojjiCore\sound\Enrage.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Escort|r", [[Interface\Addons\FojjiCore\sound\Escort.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Exit|r", [[Interface\Addons\FojjiCore\sound\Exit.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Exposed|r", [[Interface\Addons\FojjiCore\sound\Exposed.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Face Away Soon|r", [[Interface\Addons\FojjiCore\sound\Face Away Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Face in 2|r", [[Interface\Addons\FojjiCore\sound\Face Away in 2.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Face in 1|r", [[Interface\Addons\FojjiCore\sound\Face Away in 1.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Fallout Bat|r", [[Interface\Addons\FojjiCore\sound\Fallout Bat.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Fear|r", [[Interface\Addons\FojjiCore\sound\Fear.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Feast|r", [[Interface\Addons\FojjiCore\sound\Feast.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Fire|r", [[Interface\Addons\FojjiCore\sound\Fire.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Fire Add|r", [[Interface\Addons\FojjiCore\sound\Fire Add.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Fixate|r", [[Interface\Addons\FojjiCore\sound\Fixate.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Flame|r", [[Interface\Addons\FojjiCore\sound\Flame.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Flame Soon|r", [[Interface\Addons\FojjiCore\sound\Flame Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Flame Destruction|r", [[Interface\Addons\FojjiCore\sound\Flame Destruction.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Flames|r", [[Interface\Addons\FojjiCore\sound\Flames.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Flare|r", [[Interface\Addons\FojjiCore\sound\Flare.ogg]])
LSM:Register("sound", "fojji |cFFFF0000First|r", [[Interface\Addons\FojjiCore\sound\First.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Foji|r", [[Interface\Addons\FojjiCore\sound\Foji.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Front|r", [[Interface\Addons\FojjiCore\sound\Front.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Frontal|r", [[Interface\Addons\FojjiCore\sound\Frontal.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Frozen|r", [[Interface\Addons\FojjiCore\sound\Frozen.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Frenzy|r", [[Interface\Addons\FojjiCore\sound\Frenzy.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Frenzied Regeneration|r", [[Interface\Addons\FojjiCore\sound\Frenzied Regeneration.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Frost|r", [[Interface\Addons\FojjiCore\sound\Frost.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Full Corruption|r", [[Interface\Addons\FojjiCore\sound\Full Corruption.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Gather|r", [[Interface\Addons\FojjiCore\sound\Gather.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Gate|r", [[Interface\Addons\FojjiCore\sound\Gate.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Generator|r", [[Interface\Addons\FojjiCore\sound\Generator.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Get in the Air|r", [[Interface\Addons\FojjiCore\sound\Get in the Air.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Get Grounded|r", [[Interface\Addons\FojjiCore\sound\Get Grounded.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Ghost|r", [[Interface\Addons\FojjiCore\sound\Ghost.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Glaciate|r", [[Interface\Addons\FojjiCore\sound\Glaciate.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Glaciate Soon|r", [[Interface\Addons\FojjiCore\sound\Glaciate Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Goo|r", [[Interface\Addons\FojjiCore\sound\Goo.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Greatness|r", [[Interface\Addons\FojjiCore\sound\Greatness.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Green|r", [[Interface\Addons\FojjiCore\sound\Green.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Green Ooze|r", [[Interface\Addons\FojjiCore\sound\Green Ooze.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Guardian|r", [[Interface\Addons\FojjiCore\sound\Guardian.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Grip|r", [[Interface\Addons\FojjiCore\sound\Grip.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Ground Phase|r", [[Interface\Addons\FojjiCore\sound\Ground Phase.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Haste|r", [[Interface\Addons\FojjiCore\sound\Haste.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Hand Sac|r", [[Interface\Addons\FojjiCore\sound\Hand Sac.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Healcd|r", [[Interface\Addons\FojjiCore\sound\Healcd.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Healthstone|r", [[Interface\Addons\FojjiCore\sound\Healthstone.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Heart of Ice|r", [[Interface\Addons\FojjiCore\sound\Heart of Ice.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Hide|r", [[Interface\Addons\FojjiCore\sound\Hide.ogg]])
LSM:Register("sound", "fojji |cFFFF0000High Corruption|r", [[Interface\Addons\FojjiCore\sound\High Corruption.ogg]])
LSM:Register("sound", "fojji |cFFFF0000High Energy|r", [[Interface\Addons\FojjiCore\sound\High Energy.ogg]])
LSM:Register("sound", "fojji |cFFFF0000High Stacks|r", [[Interface\Addons\FojjiCore\sound\High Stacks.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Hook Launched|r", [[Interface\Addons\FojjiCore\sound\Hook Launched.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Hurricane|r", [[Interface\Addons\FojjiCore\sound\Hurricane.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Ice|r", [[Interface\Addons\FojjiCore\sound\Ice.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Ice Patch|r", [[Interface\Addons\FojjiCore\sound\Ice Patch.ogg]])
LSM:Register("sound", "fojji |cFFFF0000IBF|r", [[Interface\Addons\FojjiCore\sound\IBF.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Impale|r", [[Interface\Addons\FojjiCore\sound\Impale.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Immunity|r", [[Interface\Addons\FojjiCore\sound\Immunity.ogg]])
LSM:Register("sound", "fojji |cFFFF0000In|r", [[Interface\Addons\FojjiCore\sound\In.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Infection|r", [[Interface\Addons\FojjiCore\sound\Infection.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Infusion|r", [[Interface\Addons\FojjiCore\sound\Infusion.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Innervate|r", [[Interface\Addons\FojjiCore\sound\Innervate.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Invisibility|r", [[Interface\Addons\FojjiCore\sound\Invisibility.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Intermission|r", [[Interface\Addons\FojjiCore\sound\Intermission.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Interrupt|r", [[Interface\Addons\FojjiCore\sound\Interrupt.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Jets|r", [[Interface\Addons\FojjiCore\sound\Jets.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Jets Soon|r", [[Interface\Addons\FojjiCore\sound\Jets Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Judgement|r", [[Interface\Addons\FojjiCore\sound\Judgement.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Jump|r", [[Interface\Addons\FojjiCore\sound\Jump.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Jump in 2|r", [[Interface\Addons\FojjiCore\sound\Jump in 2.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Kite|r", [[Interface\Addons\FojjiCore\sound\Kite.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Knock|r", [[Interface\Addons\FojjiCore\sound\Knock.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Knockback|r", [[Interface\Addons\FojjiCore\sound\Knockback.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Knockback in 3|r", [[Interface\Addons\FojjiCore\sound\Knockback in 3.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Knockback in 5|r", [[Interface\Addons\FojjiCore\sound\Knockback in 5.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Last Stand|r", [[Interface\Addons\FojjiCore\sound\Last Stand.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Lava Seeds|r", [[Interface\Addons\FojjiCore\sound\Lava Seeds.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Lava Spew|r", [[Interface\Addons\FojjiCore\sound\Lava Spew.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Left|r", [[Interface\Addons\FojjiCore\sound\Left.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Life Grip|r", [[Interface\Addons\FojjiCore\sound\Life Grip.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Life Tap|r", [[Interface\Addons\FojjiCore\sound\Life Tap.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Lightning Rod in 5|r", [[Interface\Addons\FojjiCore\sound\Lighning Rod in 5.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Lightsaber|r", [[Interface\Addons\FojjiCore\sound\Lightsaber.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Linked|r", [[Interface\Addons\FojjiCore\sound\Linked.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Look for Meteor|r", [[Interface\Addons\FojjiCore\sound\Look for Meteor.ogg]])
LSM:Register("sound", "fojji |cFFFF0000LoS|r", [[Interface\Addons\FojjiCore\sound\LoS.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Low Health|r", [[Interface\Addons\FojjiCore\sound\Low Health.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Magmatron|r", [[Interface\Addons\FojjiCore\sound\Magmatron.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Mana Hymn|r", [[Interface\Addons\FojjiCore\sound\Mana Hymn.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Mana Tide|r", [[Interface\Addons\FojjiCore\sound\Mana Tide.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Mark|r", [[Interface\Addons\FojjiCore\sound\Mark.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Mass Dispell|r", [[Interface\Addons\FojjiCore\sound\Mass Dispell.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Massacre|r", [[Interface\Addons\FojjiCore\sound\Massacre.ogg]])
LSM:Register("sound", "fojji |cFFFF0000MC|r", [[Interface\Addons\FojjiCore\sound\MC.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Melee|r", [[Interface\Addons\FojjiCore\sound\Melee.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Meteor|r", [[Interface\Addons\FojjiCore\sound\Meteor.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Move|r", [[Interface\Addons\FojjiCore\sound\Move.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Move Adds|r", [[Interface\Addons\FojjiCore\sound\Move Adds.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Move Full|r", [[Interface\Addons\FojjiCore\sound\Move Full.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Move Once|r", [[Interface\Addons\FojjiCore\sound\Move Once.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Move Out|r", [[Interface\Addons\FojjiCore\sound\Move Out.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Newb|r", [[Interface\Addons\FojjiCore\sound\Newb.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Next|r", [[Interface\Addons\FojjiCore\sound\Next.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Numen|r", [[Interface\Addons\FojjiCore\sound\Numen.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Ooze|r", [[Interface\Addons\FojjiCore\sound\Ooze.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Orange|r", [[Interface\Addons\FojjiCore\sound\Orange.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Orb|r", [[Interface\Addons\FojjiCore\sound\Orb.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Out|r", [[Interface\Addons\FojjiCore\sound\Out.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Overlap|r", [[Interface\Addons\FojjiCore\sound\Overlap.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Overcharged|r", [[Interface\Addons\FojjiCore\sound\Overcharged.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Parasite|r", [[Interface\Addons\FojjiCore\sound\Parasite.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Personal|r", [[Interface\Addons\FojjiCore\sound\Personal.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Phase2|r", [[Interface\Addons\FojjiCore\sound\Phase2.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Phase3|r", [[Interface\Addons\FojjiCore\sound\Phase3.ogg]])
LSM:Register("sound", "fojji |cFFFF0000PI|r", [[Interface\Addons\FojjiCore\sound\PI.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Pips|r", [[Interface\Addons\FojjiCore\sound\Pips.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Plague|r", [[Interface\Addons\FojjiCore\sound\Plague.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Pool Growing|r", [[Interface\Addons\FojjiCore\sound\Pool Growing.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Possible Failure|r", [[Interface\Addons\FojjiCore\sound\Possible Failure.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Pots|r", [[Interface\Addons\FojjiCore\sound\Pots.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Pull|r", [[Interface\Addons\FojjiCore\sound\Pull.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Purple|r", [[Interface\Addons\FojjiCore\sound\Purple.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Push|r", [[Interface\Addons\FojjiCore\sound\Push.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Quake|r", [[Interface\Addons\FojjiCore\sound\Quake.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Range|r", [[Interface\Addons\FojjiCore\sound\Range.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Ready|r", [[Interface\Addons\FojjiCore\sound\Ready.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Red|r", [[Interface\Addons\FojjiCore\sound\Red.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Red Ooze|r", [[Interface\Addons\FojjiCore\sound\Red Ooze.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Reflect|r", [[Interface\Addons\FojjiCore\sound\Reflect.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Remedy|r", [[Interface\Addons\FojjiCore\sound\Remedy.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Right|r", [[Interface\Addons\FojjiCore\sound\Right.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Rings|r", [[Interface\Addons\FojjiCore\sound\Rings.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Rally|r", [[Interface\Addons\FojjiCore\sound\Rally.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Rallying Cry|r", [[Interface\Addons\FojjiCore\sound\Rallying Cry.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Roar Soon|r", [[Interface\Addons\FojjiCore\sound\Roar Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Rod in 5|r", [[Interface\Addons\FojjiCore\sound\Rod in 5.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Rods in 5|r", [[Interface\Addons\FojjiCore\sound\Rods in 5.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Rod on You|r", [[Interface\Addons\FojjiCore\sound\Rod on You.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Run|r", [[Interface\Addons\FojjiCore\sound\Run.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Run Out|r", [[Interface\Addons\FojjiCore\sound\Run Out.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Rune|r", [[Interface\Addons\FojjiCore\sound\Rune.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Sacred Shield|r", [[Interface\Addons\FojjiCore\sound\Sacred Shield.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Salvation|r", [[Interface\Addons\FojjiCore\sound\Salvation.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Scale|r", [[Interface\Addons\FojjiCore\sound\Scale.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Selfcd|r", [[Interface\Addons\FojjiCore\sound\Selfcd.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Shadow Add|r", [[Interface\Addons\FojjiCore\sound\Shadow Add.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Shadowblaze|r", [[Interface\Addons\FojjiCore\sound\Shadowblaze.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Shadow Infused|r", [[Interface\Addons\FojjiCore\sound\Shadow Infused.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Shield|r", [[Interface\Addons\FojjiCore\sound\Shield.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Shield Soon|r", [[Interface\Addons\FojjiCore\sound\Shield Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Shield Wall|r", [[Interface\Addons\FojjiCore\sound\Shield Wall.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Sham Rage|r", [[Interface\Addons\FojjiCore\sound\Sham Rage.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Sickness|r", [[Interface\Addons\FojjiCore\sound\Sickness.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Silenced|r", [[Interface\Addons\FojjiCore\sound\Silenced.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Skeleton|r", [[Interface\Addons\FojjiCore\sound\Skeleton.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Slicers|r", [[Interface\Addons\FojjiCore\sound\Slicers.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Snap|r", [[Interface\Addons\FojjiCore\sound\Snap.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Soak|r", [[Interface\Addons\FojjiCore\sound\Soak.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Soon|r", [[Interface\Addons\FojjiCore\sound\Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Soulwell|r", [[Interface\Addons\FojjiCore\sound\Soulwell.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Spawn|r", [[Interface\Addons\FojjiCore\sound\Spawn.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Special Soon|r", [[Interface\Addons\FojjiCore\sound\Special Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Spellsteal|r", [[Interface\Addons\FojjiCore\sound\Spellsteal.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Spirit|r", [[Interface\Addons\FojjiCore\sound\Spirit.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Split|r", [[Interface\Addons\FojjiCore\sound\Split.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Spikes|r", [[Interface\Addons\FojjiCore\sound\Spikes.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Spore|r", [[Interface\Addons\FojjiCore\sound\Spore.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Spray|r", [[Interface\Addons\FojjiCore\sound\Spray.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Spread|r", [[Interface\Addons\FojjiCore\sound\Spread.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Stack|r", [[Interface\Addons\FojjiCore\sound\Stack.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Stack on Debuff|r", [[Interface\Addons\FojjiCore\sound\Stack on Debuff.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Static|r", [[Interface\Addons\FojjiCore\sound\Static.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Stop|r", [[Interface\Addons\FojjiCore\sound\Stop.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Stop Attack|r", [[Interface\Addons\FojjiCore\sound\Stop Attack.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Stopcast|r", [[Interface\Addons\FojjiCore\sound\Stopcast.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Strength|r", [[Interface\Addons\FojjiCore\sound\Strength.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Stun|r", [[Interface\Addons\FojjiCore\sound\Stun.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Stun Now|r", [[Interface\Addons\FojjiCore\sound\Stun Now.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Stunned|r", [[Interface\Addons\FojjiCore\sound\Stunned.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Summon|r", [[Interface\Addons\FojjiCore\sound\Summon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Survival Instincts|r", [[Interface\Addons\FojjiCore\sound\Survival Instincts.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Swirlies|r", [[Interface\Addons\FojjiCore\sound\Swirlies.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Swap Trinket|r", [[Interface\Addons\FojjiCore\sound\Swap Trinket.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Systems Failure|r", [[Interface\Addons\FojjiCore\sound\Systems Failure.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Table|r", [[Interface\Addons\FojjiCore\sound\Table.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Targeted|r", [[Interface\Addons\FojjiCore\sound\Targeted.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Target Encased|r", [[Interface\Addons\FojjiCore\sound\Target Encased.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Targeting|r", [[Interface\Addons\FojjiCore\sound\Targeting.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Taunt|r", [[Interface\Addons\FojjiCore\sound\Taunt.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Threat|r", [[Interface\Addons\FojjiCore\sound\Threat.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Third|r", [[Interface\Addons\FojjiCore\sound\Third.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Thundershock|r", [[Interface\Addons\FojjiCore\sound\Thundershock.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Toxitron|r", [[Interface\Addons\FojjiCore\sound\Tox etron.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Time Warp|r", [[Interface\Addons\FojjiCore\sound\Time Warp.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Tornado|r", [[Interface\Addons\FojjiCore\sound\Tornado.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Totem|r", [[Interface\Addons\FojjiCore\sound\Totem.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Touch Fire|r", [[Interface\Addons\FojjiCore\sound\Touch Fire.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Transition|r", [[Interface\Addons\FojjiCore\sound\Transition.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Trap|r", [[Interface\Addons\FojjiCore\sound\Trap.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Tremor|r", [[Interface\Addons\FojjiCore\sound\Tremor.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Tricks|r", [[Interface\Addons\FojjiCore\sound\Tricks.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Trinket|r", [[Interface\Addons\FojjiCore\sound\Trinket.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Turn|r", [[Interface\Addons\FojjiCore\sound\Turn.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Unstable|r", [[Interface\Addons\FojjiCore\sound\Unstable.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Use Pot|r", [[Interface\Addons\FojjiCore\sound\Use Pot.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Vampiric Blood|r", [[Interface\Addons\FojjiCore\sound\Vampiric Blood.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Ward|r", [[Interface\Addons\FojjiCore\sound\Ward.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Watch for Deep Breaths|r", [[Interface\Addons\FojjiCore\sound\Watch for Deep Breaths.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Watch Threat|r", [[Interface\Addons\FojjiCore\sound\Watch Threat.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Watch your feet|r", [[Interface\Addons\FojjiCore\sound\Watch your feet.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Whelps|r", [[Interface\Addons\FojjiCore\sound\Whelps.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Wind Blast in 5|r", [[Interface\Addons\FojjiCore\sound\Wind Blast in 5.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Wind Burst Soon|r", [[Interface\Addons\FojjiCore\sound\Wind Burst Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Wind Burst|r", [[Interface\Addons\FojjiCore\sound\Wind Burst.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Winds|r", [[Interface\Addons\FojjiCore\sound\Winds.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Yellow|r", [[Interface\Addons\FojjiCore\sound\Yellow.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Zone|r", [[Interface\Addons\FojjiCore\sound\Zone.ogg]])


-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "fojjiBlank", [[Interface\Addons\FojjiCore\statusbar\fojjiBlank.tga]])
LSM:Register("statusbar", "fojjiFlat", [[Interface\Addons\FojjiCore\statusbar\fojjiFlat.tga]])
LSM:Register("statusbar", "fojjiKUI", [[Interface\Addons\FojjiCore\statusbar\fojjiKUI.tga]])
LSM:Register("statusbar", "fojjiMelli", [[Interface\Addons\FojjiCore\statusbar\Melli.tga]])