local addonName = "RecipesCollector"
local RC = _G.LibStub("AceAddon-3.0"):GetAddon(addonName)

RC.ProfessionNames = {
    enUS = {
        "Blacksmithing",
        "Leatherworking",
        "Alchemy",
        "Herbalism",
        "Cooking",
        "Mining",
        "Tailoring",
        "Engineering",
        "Enchanting",
        "Fishing",
        "Skinning",
        "Jewelcrafting",
        "First Aid",
        "Inscription",
    },
    deDE = {
        "Schmiedekunst",
        "Lederverarbeitung",
        "Alchemie",
        "Kräuterkunde",
        "Kochkunst",
        "Bergbau",
        "Schneiderei",
        "Ingenieurskunst",
        "Verzauberkunst",
        "Angeln",
        "Kürschnerei",
        "Juwelierskunst",
        "Erste Hilfe",
        "Inschriftenkunde",
    },
    frFR = {
        "Forge",
        "Travail du cuir",
        "Alchimie",
        "Herboristerie",
        "Cuisine",
        "Minage",
        "Couture",
        "Ingénierie",
        "Enchantement",
        "Pêche",
        "Dépeçage",
        "Joaillerie",
        "Secourisme",
        "Calligraphie",
    },
    esMX = {
        "Herrería",
        "Peletería",
        "Alquimia",
        "Herboristería",
        "Cocina",
        "Minería",
        "Sastrería",
        "Ingeniería",
        "Encantamiento",
        "Pesca",
        "Desuello",
        "Joyería",
        "Primeros auxilios",
        "Inscripción",
    },
    ptBR = {
        "Ferraria",
        "Couraria",
        "Alquimia",
        "Herborismo",
        "Culinária",
        "Mineração",
        "Alfaiataria",
        "Engenharia",
        "Encantamento",
        "Pesca",
        "Esfolamento",
        "Joalheria",
        "Primeiros Socorros",
        "Escrivania",
    },
    ruRU = {
        "Кузнечное дело",
        "Кожевничество",
        "Алхимия",
        "Травничество",
        "Кулинария",
        "Горное дело",
        "Портняжное дело",
        "Инженерное дело",
        "Наложение чар",
        "Рыбная ловля",
        "Снятие шкур",
        "Ювелирное дело",
        "Первая помощь",
        "Начертание",
    },
    zhCN = {
        "锻造",
        "制皮",
        "炼金术",
        "草药学",
        "烹饪",
        "采矿",
        "裁缝",
        "工程学",
        "附魔",
        "钓鱼",
        "剥皮",
        "珠宝加工",
        "急救",
        "铭文",
    },
    zhTW = {
        "鍛造",
        "製皮",
        "鍊金術",
        "草藥學",
        "烹飪",
        "採礦",
        "裁縫",
        "工程學",
        "附魔",
        "釣魚",
        "剝皮",
        "珠寶設計",
        "急救",
        "銘文學",
    },
    koKR = {
        "대장기술",
        "가죽세공",
        "연금술",
        "약초채집",
        "요리",
        "채광",
        "재봉술",
        "기계공학",
        "마법부여",
        "낚시",
        "무두질",
        "보석세공",
        "응급치료",
        "주문각인",
    },
}
