if GetLocale() ~= "zhCN" then
    return
end

local L = LibStub("AceLocale-3.0"):NewLocale("GSE", "zhCN")

-- Options translation
L[" was imported."] = "已导入。"
L["%s/255 Characters Used"] = "已使用 %s/255 个字符"
L[", You will need to correct errors in this variable from another source."] = "，您需要从其他来源更正此变量中的错误。"
L["Account Macros"] = "账户宏"
L["Action Type"] = "操作类型"
L["Actionbar Buttons"] = "动作条按钮"
L["Actionbar Overrides"] = "动作条覆盖"
L["Add Special KeyBinding"] = "添加特殊按键绑定"
L["Add Talent Loadout"] = "添加天赋配置"
L["Advanced Export"] = "高级导出"
L["All Talent Loadouts"] = "所有天赋配置"
L["Already Known"] = "已学会"
L["Button State"] = "按钮状态"
--[[Translation missing --]]
L["CHanges Left Side, Changes Right Side, Many Changes!!!! Handle It"] = "CHanges Left Side, Changes Right Side, Many Changes!!!! Handle It"
L["Changes Left Side, Changes Right Side, Many Changes!!!! Handle It!"] = "左侧更改、右侧更改、多项更改！！！处理它！"
L["Character Macros"] = "角色宏"
L["Chat Link"] = "聊天链接"
L["Command Colour"] = "命令颜色"
L["Compiled Macro"] = "已编译宏"
L["Conditionals Colour"] = "条件颜色"
L["Create a new macro in the /macro interface and assign it an Icon. Then reopen this menu.  You cannot create a new macro here but after it has been created you can manage it."] = "在 /macro 界面创建新宏并分配图标，然后重新打开此菜单。您不能在此处创建新宏，但创建后可以管理它。"
L["Create Human Readable Exports"] = "创建人类可读的导出"
L["Current Value"] = "当前值"
L["Default"] = "默认"
L["Default Keybinding Height"] = "默认按键绑定高度"
L["Default Keybinding Width"] = "默认按键绑定宽度"
L["Disable inbuilt LibActionButton"] = "禁用内置 LibActionButton"
L["Disable Sequence"] = "禁用序列"
L["Do not compile this Sequence at startup."] = "启动时不编译此序列。"
L["Enable Mod Debug Mode"] = "启用模块调试模式"
L["Enter the implementation link for this variable. Use '= true' or '= false' to test."] = "输入此变量的实现链接。使用 '= true' 或 '= false' 进行测试。"
L["Experimental Features"] = "实验性功能"
L["Export Variable"] = "导出变量"
--[[Translation missing --]]
L["Gnome Sequencer Enhanced"] = "Gnome Sequencer Enhanced"
L["GSE allows plugins to load Collections as plugins.  You can reload a collection by pressing the button below."] = "GSE 允许插件以插件形式加载集合。按下下方按钮可重新加载集合。"
L["GSE Discord"] = "GSE Discord"
L["GSE has a LibDataBroker (LDB) data feed.  Set this option to show queued Out of Combat events in the tooltip."] = "GSE有一个LibDataBroker（LDB）数据源.设置此选项可在提示中显示序列中的战斗外事件."
L["GSE: Export"] = "GSE：导出"
L["GSE: Main Menu"] = "GSE：主菜单"
L["GSE: Middle Click to open the Keybinding Interface"] = "GSE: 中键单击以打开按键绑定界面"
L["GSE: Record your rotation to a macro."] = "GSE：将您的循环录制为宏。"
L["GSE: Whats New in "] = "GSE：新增内容 "
L["How many pixels high should Keybindings start at.  Defaults to 500"] = "按键绑定初始高度像素数（默认 500）"
L["How many pixels wide should Keybinding start at.  Defaults to 700"] = "按键绑定初始宽度像素数（默认 700）"
L["How many times does this action repeat"] = "此动作重复多少次"
L["Implementation Link"] = "实现链接"
L["Import Macro from Forums"] = "从论坛导入宏"
L["Insert Gamepad KeyBind"] = "插入手柄按键绑定"
L["Insert GSE Sequence"] = "插入 GSE 序列"
L["Insert GSE Variable"] = "插入 GSE 变量"
L["Insert Mouse KeyBind"] = "插入鼠标按键绑定"
L["Insert Spell"] = "插入法术"
L["Insert Test Case"] = "插入测试用例"
L["Item"] = "物品"
L["Keybind"] = "按键绑定"
L["Keybindings"] = "按键绑定"
L["Last Updated"] = "最后更新"
L["Left Mouse Button"] = "鼠标左键"
L["LibActionButton is used by ConsolePort and Bartender.  Disabling this will use the standard version of this library."] = "ConsolePort 和 Bartender 使用 LibActionButton。禁用将使用此库的标准版本。"
L["Macro"] = "宏"
L["Macro Name"] = "宏名称"
L["Macro Name or Macro Commands"] = "宏名称或宏命令"
L["Macro Template"] = "宏模板"
L["Macros"] = "宏"
L["Manage Keybinds"] = "管理按键绑定"
L["Manage Macro"] = "管理宏"
L["Manage Macro with GSE"] = "使用 GSE 管理宏"
L["Manage Macros"] = "管理宏"
L["Manage Variables"] = "管理变量"
L["Missing Variable "] = "缺失变量 "
L["modified in other window.  This view is now behind the current sequence."] = "在其他窗口中修改。该视图现在位于当前序列之后。"
L["New Actionbar Override"] = "新建动作条覆盖"
L["New KeyBind"] = "新的按键绑定"
L["New Sequence"] = "新建序列"
L["New Variable"] = "新建变量"
L["Not Yet Active"] = "尚未激活"
L["Open %s in New Window"] = "在新窗口中打开%s"
L["Party"] = "小队"
L["Pet"] = "宠物"
L["Pet Ability"] = "宠物技能"
L["Print Active Modifiers on Click"] = "点击时在聊天框显示激活的修饰键"
L["Processing Collection of %s Elements."] = "正在处理 %s 个元素的集合。"
L["Repeat"] = "重复"
L["Report an Issue"] = "报告问题"
L["Right Mouse Button"] = "鼠标右键"
L["Save pending for "] = "保存等待中 "
L["Save the changes made to this variable."] = "保存对此变量的更改。"
L["Saved"] = "已保存"
L["Select Icon"] = "选择图标"
L["Sequences"] = "序列"
L["Set Key to Bind"] = "设置绑定键"
L["Show next time you login."] = "下次登录时显示。"
L["Spell"] = "法术"
L["Store output of debug messages in a Global Variable that can be referrenced by other mods."] = "将调试消息的输出存储在可由其他mod引用的全局变量中."
L["String Colour"] = "字符串颜色"
L["Talent Loadout"] = "天赋配置"
L["The author of this Macro."] = "此宏的作者。"
L["The author of this Variable."] = "此变量的作者。"
L["The UI has been set to KeyDown configuration.  The /click command needs to be `/click TEMPLATENAME LeftButton t` (Note the 't' here is required along with the LeftButton.)  You will need to check your macros and adjust your click commands."] = "界面已设为按键按下配置。/click 命令需为 “/click 模板名 LeftButton t”（注意此处的 't' 需与 LeftButton 一起使用）。请检查宏并调整点击命令。"
L["The UI has been set to KeyUp configuration.  The /click command needs to be `/click TEMPLATENAME` You will need to check your macros and adjust your click commands."] = "界面已设为按键松开配置。/click 命令需为 “/click 模板名”。请检查宏并调整点击命令。"
L["There is an error in the sequence that needs to be corrected before it can be saved."] = "序列中存在需要纠正的错误才能保存。"
L["There was an error processing "] = "处理时出错 "
L["This macro is not compatible with this version of the game and cannot be imported."] = "此宏与当前游戏版本不兼容，无法导入。"
L["This option dumps extra trace information to your chat window to help troubleshoot problems with the mod"] = "此选项将额外的跟踪信息转储到聊天窗口,以帮助解决模块的问题"
L["This version of GSE is incompatabile with this version of the game."] = "此版本 GSE 与当前游戏版本不兼容。"
L["Toy"] = "玩具"
L["Unit Name"] = "单位名称"
L["Use WLM Export Sequence Format"] = "使用WLM格式导出序列"
L["Variable"] = "变量"
L["Variable Menu"] = "变量菜单"
--[[Translation missing --]]
L["WhatsNew"] = [=[|cFFFFFFFFGS|r|cFF00FFFFE|r 3.2.25 has finally fixed being able to use castsequences and their resets within GSE.

The GUI Menu and the Editor have been redesigned.  Details are in Discord.]=]
L["When creating a macro, if there is not a personal character macro space, create an account wide macro."] = "创建宏时,如果没有角色宏空间,创建帐户通用的宏."
L["When exporting from GSE create a descriptive export for Discord/Discource forums."] = "从 GSE 导出时创建适合 Discord/Discourse 论坛的描述性导出。"
L["When loading or creating a sequence, if it is a macro of the same class automatically create the Macro Stub"] = "当加载或创建序列时,如果它是同职业的宏,则自动创建宏存根"
L["You cannot open a new Sequence Editor window while you are in combat.  Please exit combat and then try again."] = "在战斗中无法打开新的序列编辑器窗口。请退出战斗，然后重试。"


